// Do not edit this file manually it is auto-generated during the build based on the .resx file for this project.
namespace System
{
    internal class SR : System.Collections.Immutable.Resources.Strings
    {
        private SR()
        {
        }
    }
}
